### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Jaedotmoe** [TryGhost/London#129]
Automatic dark theme based on the OS preference like:
```css
@media screen and (prefers-color-scheme: light) {
    body {
        background-color: #FFF;
        color: #212121;
    }
    a {
        color: #7E57C2;
    }
}
```
It would improve readability for some users.
