### ISSUE TITLE
Sans serif font variable is not used in body

### ISSUE THREAD

**Issue by dhruvkb** [TryGhost/London#28]
The CSS file `vars.css` allows modifications to the default sans-serif font by customising the variable `--font-sans-serif`.

```css
:root {
  --font-sans-serif: 'Font Name', sans-serif;
  ...
}
```

This modification does not reflect in the document body because `screen.css` has the font-family name hardcoded as 'Muli'.

```css
body {
  font-family: 'Muli', sans-serif;
}
```

This hardcoded value should be replaced with `var(--font-sans-serif)` if I'm understanding correctly.
